import time
import os

while 1:
	print("hello,guss who am i?")
	print("ok, i am:")
	time.sleep(3)
	print("######  ##  ##  #####   ######  ######  ##    ##  ##  ##      ##     ##      ##")
	print("#       ##  ##  ##  ##  ##      ##  ##   ##  ##   ##  ##    ##  ##   ## ##   ##")
	print("#       ##  ##  ##  ##  ##      ## ##      ##     ##  ##   ##    ##  ##      ##")
	print("######  ##  ##  ####    ######  ###        ##     ##  ##   ########  ##  ##  ##")
	print("     #  ##  ##  ##      ##      ## ##      ##     ##  ##   ##    ##  ##      ##")
	print("     #  ##  ##  ##      ##      ##  ##     ##     ##  ##   ##    ##  ##    ####")
	print("######  ######  ##      ######  ##   ##    ##     ######   ##    ##  ##      ##")
	time.sleep(5)
	print("when i saw you for the first time:")
	time.sleep(1)
	print("you know what?")
	time.sleep(1)
	print("i loved you ")
	time.sleep(1)
	print("i do not want anything but your love")
	time.sleep(1)
	print("so")
	time.sleep(1)
	print("please let me say someting to you")
	time.sleep(1)
	print("i love you")
	time.sleep(1)
	print("look at my heart:")
	time.sleep(5)
	print("#####################")
	print("#   **         **   #")
	print("#**    **   **    **#")
	print("#**       *       **#")
	print("# **             ** #")
	print("#  **           **  #")
	print("#   **         **   #")
	print("#     **     **     #")
	print("#       ** **       #")
	print("#         *         #")
	print("#####################")
	input("you are the best!")
	break